"""create collection tables

Revision ID: 499d75f87b51
Revises: f1d473a23084
Create Date: 2026-06-14 17:06:14.622247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499d75f87b51'
down_revision: Union[str, Sequence[str], None] = 'f1d473a23084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('cabin', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_user_tracked', sa.Boolean(), nullable=False),
    sa.Column('wishlist_item_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('cabin', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cheapest_price_cents', sa.Integer(), nullable=False),
    sa.Column('mean_top_n_price_cents', sa.Integer(), nullable=True),
    sa.Column('n_offers', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_route_observed', 'price_history', ['origin', 'destination', 'departure_date', 'observed_at'], unique=False)
    op.create_table('api_responses_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('poll_target_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poll_target_id'], ['poll_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_offers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_response_id', sa.BigInteger(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('cabin', sa.String(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('fare_brand', sa.String(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_response_id'], ['api_responses_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_offers_route_observed', 'flight_offers', ['origin', 'destination', 'departure_date', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flight_offers_route_observed', table_name='flight_offers')
    op.drop_table('flight_offers')
    op.drop_table('api_responses_raw')
    op.drop_index('ix_price_history_route_observed', table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('poll_targets')
    # ### end Alembic commands ###
